In [1]:
import numpy as np

In [10]:
#Сколько решений имеет линейная система:

A = np.array([[1, 2, 3], [4, 5 , 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A, B.T), axis=1)
print(C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)
#Так как ранг отличается, значит решений нет. Подберем правый вектор

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

In [13]:
A = np.array([[1, 2, 3], [4, 5 , 6], [7, 8, 9]])
D = np.array([[1, 2, 3]])
C0 = np.concatenate((A, D.T), axis=1)
print(C0)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C0, 0.0001)
#Теперь ранг совпадает, значит есть решение! Найдем.

[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 3]]


(2, 2)

In [12]:
# Решение:
A = np.array([[1, 2, 3], [4, 5 , 6], [7, 8, 9]])
D = np.array([1, 2, 3])
np.linalg.solve(A, D)

array([-0.23333333,  0.46666667,  0.1       ])